apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-pccihppz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-pccihppz 
  name: go-pccihppz
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-pccihppz 
